[package]
name = "prac_macro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prac_macro_derive = { path = "prac_macro_derive" }